apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lb-apps
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        nginx-homepage-configmap-version: "v1.0.4"
    spec:
      containers:
      - name: nginx
        image: container-registry.oracle.com/olcne/nginx:1.17.7
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-homepage-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
        - -nginx.scrape-uri=http://localhost/stub_status
        ports:
        - containerPort: 9113
          name: metrics
      volumes:
      - name: nginx-homepage-volume
        configMap:
          name: nginx-homepage-content
      - name: nginx-config-volume
        configMap:
          name: nginx-homepage-content
