# nginx-oci/nginx-homepage-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-homepage-content
  namespace: lb-apps # Assuming your Nginx deployment is in this namespace
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Nginx OCI Homepage</title>
        <style>
            body { font-family: Arial, sans-serif; background-color: #f0f0f0; text-align: center; padding-top: 50px; }
            h1 { color: #333; }
            p { color: #666; }
        </style>
    </head>
    <body>
        <h1>Hello from my Argo CD Nginx (OCI) Deployment!</h1>
        <p>This page was updated using a ConfigMap.</p>
        <p>Current time in India: June 3, 2025 (as of your last prompt)</p>
    </body>
    </html>
