apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-homepage-content
  namespace: lb-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Nginx OCI Homepage</title>
        <style>
            body { font-family: Arial, sans-serif; background-color: #f0f0f0; text-align: center; padding-top: 50px; }
            h1 { color: #333; }
            p { color: #666; }
        </style>
    </head>
    <body>
        <h1>Hello from my Argo CD Nginx Deployment!</h1>
        <p>Welcome to OCNE 2.1 CI/CD Demo.</p>
        <p>This page was updated using a ConfigMap.</p>
        <div class="link-container">
            <p>Visit: <a href="https://www.oracle.com" target="_blank">oracle.com</a></p>
        </div>        
        <form action="https://www.google.com/search" method="get">
          <input type="search" name="q" placeholder="Google Search">
          <button type="submit">Search</button>
        </form>
        <p>Current time in India: </p>
        <p id="datetime"></p>
        <script>
          var now = new Date();
          var datetime = now.toLocaleDateString() + " " + now.toLocaleTimeString();
          document.getElementById("datetime").innerHTML = datetime;
        </script>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html;
            }
            location /stub_status {
                stub_status on;
                allow 127.0.0.1; # Allow only localhost (exporter will access it)
                deny all;
            }
        }
    }
